### ISSUE TITLE
after Including it completely mess up my project in webpack

### ISSUE THREAD

**Issue by SaniHaque** [jdotrjs/phaser3-nineslice#15]
`[ ChunkRenderError: Conflict: Multiple chunks emit assets to the same filename phaser.js (chunks 1 and 2)`

` chunkFilename: '[id].[chunkhash].js' or removing 'chunkFilename' didn't solve the problem. Just showed black screen. 

`

**Comment by jdotrjs** [comment]
Hi there, as far as I know nobody else has seen this with webpack and `phaser3-nineslice`.

Can you post your webpack config or upload your project as a .zip so that I can see the context where this is happening?

Thanks!
