### ISSUE TITLE
Object cropping if its larger than canvas bounds

### ISSUE THREAD

**Issue by adrianolobo** [jdotrjs/phaser3-nineslice#17]
Hi,

I'm creating paper Scroll like background with a height that varies according to the content using nineslice plugin.
So if the content is larger than the screen size I create a scroll behavior, but all the offbounds parts of this background is being cropped.

![image](https://user-images.githubusercontent.com/13997867/50222202-b6d9cb00-037e-11e9-9344-1cc27b8692de.png)

this is the bottom part that is being cropped

![image](https://user-images.githubusercontent.com/13997867/50222330-18019e80-037f-11e9-8b8c-dd39a0caa0eb.png)

**Comment by jdotrjs** [comment]
Hm.

Can you give me a little more info on how you're drawing the contents of the dialog? I don't have any support in place right now to crop just to the center area though that seems a reasonable feature request.

The thing that confuses me, and why I need more info, is why you might be seeing only the bottom bit get drawn over the nineslice. I would expect leaking from both top and bottom based on what you describe.

**Comment by adrianolobo** [comment]
Hi,

Sorry, I think I was not very clear, its actually not an enhancement, I think its a bug.

I created this repository to show the bug: https://github.com/adrianolobo/nineslice-cropping-issue

It's hosted here: https://adrianolobo.github.io/nineslice-cropping-issue/index.html

The first element, the element is larger than the canvas by 20px, notice the right side being cropped

The second element is larger than the canvas by 10px, but its scale by 0.5, notice that it still cropping the right side.

The third element an normal element just for comparison.

The scene file: https://github.com/adrianolobo/nineslice-cropping-issue/blob/master/Scene1.js

Ps. Sorry for the delay in the response, I was in vacation, im back now

**Comment by adrianolobo** [comment]
I dug into the code and discovered that it's actually a Phaser bug, and it will be patched in the next release (3.16 i believe)

https://github.com/photonstorm/phaser/issues/4139

Thank you for your time and awesome lib.

**Comment by jdotrjs** [comment]
Oh, yay; thank you! :heart: 
Haha, I'm pretty excited I don't have to figure this one out, not gonna lie.

Going to close this as it turned out to be a bug upstream.
